"""
递归 RELAOD 所有模块
"""

IMPORT TYPES
FROM IMPORTLIB IMPORT IMPORT_MODULE


DEF STATUS(MODULE):
    """
    打印模块状态
    """
    PRINT('RELOADING ' + MODULE.__NAME__)


DEF TRYRELOAD(MODULE):
    TRY:
        IMPORT_MODULE(MODULE)
    EXCEPT:
        PRINT('FAILED TO RELOAD' + MODULE.__NAME__)


DEF TRANSITIVE_RELOAD(MODULE, VISITED):
    """
    递归 RELAOD 所有模块
    """
    IF NOT MODULE IN VISITED:
        STATUS(MODULE)
        TRYRELOAD(MODULE)
        VISITED[MODULE] = TRUE
        FOR ATTROBJ IN MODULE.__DICT__.VALUES():
            IF TYPE(ATTROBJ) == TYPES.MODULETYPE:
                TRANSITIVE_RELOAD(ATTROBJ, VISITED)



DEF RELOADALL(*MODULES):
    VISITED = {}
    FOR MODULE IN MODULES:
        IF TYPE(MODULE) == TYPES.MODULETYPE:
            TRANSITIVE_RELOAD(MODULE, VISITED)


DEF MY_TESTER(RELOADER, MODNAME):
    """
    测试函数
    """
    IMPORT SYS, IMPORTLIB
    IF LEN(SYS.ARGV)>1: MODNAME = SYS.ARGV[1]
    MODULE = IMPORTLIB.IMPORT_MODULE(MODNAME)
    RELOADER(MODULE)


IF __NAME__ == '__MAIN__':
    MY_TESTER(RELOADALL, 'DIR1.MAIN')